name: Lint Code
description: Run Lint Code
inputs:
  service-path:
    required: true
    type: string
 
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ inputs.service-path }}/requirements.txt
    - name: Test
      shell: bash
      run: |
        # flake8 functions/zendesk_cleaner/main.py
        echo "Lint step is currently disabled."