name: CI Zendesk Cleaner

on:
  push:
    paths:
      - 'functions/zendesk_cleaner/**'
  pull_request:
  workflow_dispatch:
    paths:
      - 'functions/zendesk_cleaner/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Lint code
        uses: ./.github/actions/lint
        with:
          service-path: functions/zendesk_cleaner

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Unit Test
        uses: ./.github/actions/test
        with:
          service-path: functions/zendesk_cleaner

  build-staging:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Zendesk Cleaner Lambda ZIP
        uses: ./.github/actions/build-lambda
        with:
          environment-name: staging
          service-name: zendesk-cleaner
          service-path: functions/zendesk_cleaner
          upload-artifact-name: zendesk-cleaner-zip-staging
          upload-artifact-path: zendesk_cleaner.zip
          pulumi-working-directory: infrastructure/zendesk_cleaner
          pulumi-stack: staging
          pulumi-config-passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          pulumi-backend_url: s3://0202-pulumi-state/neurion-ai/zendesk-cleaner
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

  deploy-staging:
    needs: build-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Zendesk Cleaner Lambda ZIP
        uses: ./.github/actions/deploy-lambda
        with:
          environment-name: staging
          service-name: zendesk-cleaner
          service-path: functions/zendesk_cleaner
          download-artifact-name: zendesk-cleaner-zip-staging
          pulumi-working-directory: infrastructure/zendesk_cleaner
          pulumi-stack: staging
          pulumi-config-passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          pulumi-backend_url: s3://0202-pulumi-state/neurion-ai/zendesk-cleaner
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

  build-production:
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Zendesk Cleaner Lambda ZIP
        uses: ./.github/actions/build-lambda
        with:
          environment-name: production
          service-name: zendesk-cleaner
          service-path: functions/zendesk_cleaner
          upload-artifact-name: zendesk-cleaner-zip-production
          upload-artifact-path: zendesk_cleaner.zip
          pulumi-working-directory: infrastructure/zendesk_cleaner
          pulumi-stack: production
          pulumi-config-passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          pulumi-backend_url: s3://0202-pulumi-state/neurion-ai/zendesk-cleaner
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

  deploy-production:
    needs: build-production
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Zendesk Cleaner Lambda ZIP
        uses: ./.github/actions/deploy-lambda
        with:
          environment-name: production
          service-name: zendesk-cleaner
          service-path: functions/zendesk_cleaner
          download-artifact-name: zendesk-cleaner-zip-production
          pulumi-working-directory: infrastructure/zendesk_cleaner
          pulumi-stack: production
          pulumi-config-passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          pulumi-backend_url: s3://0202-pulumi-state/neurion-ai/zendesk-cleaner
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

